apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-workload-identity-selfserviceportal-service-account
  labels:
    azure.workload.identity/use: "true"
  annotations:
    azure.workload.identity/client-id: 555-555-555-555 # managed identity client id from terraform output
    azure.workload.identity/tenant-id: 555-555-555-555
automountServiceAccountToken: false